### ISSUE TITLE
Boxing 

### ISSUE THREAD

**Issue by mallusrgreatv2** [diamond-rip/Eden#153]
Boxing + No Damage on a kit, random player instantly dies after starting.
![image](https://user-images.githubusercontent.com/69511006/223694990-9f828b73-1397-459a-b3f5-f2e711b83999.png)

**Comment by mallusrgreatv2** [comment]
[10:51:58 WARN]: [Eden] Task #53 for Eden v1.0.36-BETA-149c88e generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469) ~[?:1.8.0_312]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1503) ~[?:1.8.0_312]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1501) ~[?:1.8.0_312]
        at rip.diamond.practice.util.menu.task.MenuUpdateTask.onRun(MenuUpdateTask.java:22) ~[?:?]
        at rip.diamond.practice.util.TaskTicker.run(TaskTicker.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65) ~[server.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:403) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:927) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[server.jar:]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]

Just noticed this error.

**Comment by GoodestEnglish** [comment]
> Boxing + No Damage on a kit, random player instantly dies after starting. ![image](https://user-images.githubusercontent.com/69511006/223694990-9f828b73-1397-459a-b3f5-f2e711b83999.png)

Looks like an arena incorrectly setup error. Make sure to set your min, max, y limit correctly

**Comment by GoodestEnglish** [comment]
I've also checked about the menu error you sent and looks like it is a problem on my side. Will fix soon.
