### ISSUE TITLE
ImanitySpigot fork

### ISSUE THREAD

**Issue by xIKilleRzI** [diamond-rip/Eden#154]
[10:42:32 WARN]: [Eden] Task #17949 for Eden v1.0.36-BETA-149c88e generated an exception
java.lang.NoSuchMethodError: org.bukkit.Server$Imanity.getKnockbackService()Ldev/imanity/knockback/api/KnockbackService;
        at rip.diamond.spigotapi.knockback.impl.ImanitySpigot3Knockback.applyKnockback(ImanitySpigot3Knockback.java:12) ~[?:?]
        at rip.diamond.practice.match.Match.start(Match.java:143) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(SourceFile:410) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:948) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:868) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:769) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]

**Comment by GoodestEnglish** [comment]
You are using an outdated imanity spigot, update it.

**Comment by xIKilleRzI** [comment]
![image](https://user-images.githubusercontent.com/22942740/223721158-fc735561-420d-4a8f-b8c3-2caa68f64959.png)

**Comment by xIKilleRzI** [comment]
update to latest ?

**Comment by GoodestEnglish** [comment]
Try to update to the latest, I am using 2023-02-1b1 and can't reproduce the error.

**Comment by diocan** [comment]
try to use latest Eden
