### ISSUE TITLE
Task #42

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#173]
container@pterodactyl~ Server marked as running...
[16:39:58 INFO]: Timings Reset
[16:39:58 INFO]: No server chosen by com.mongodb.client.internal.MongoClientDelegate$1@5bc15e8b from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=n1-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}, ServerDescription{address=n2-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]}. Waiting for 30000 ms before timing out
[16:39:59 WARN]: [SkinsRestorer] Failed to get release info from api.github.com. 
 If this message is repeated a lot, please see http://skinsrestorer.net/firewall
[16:40:01 INFO]: (FAWE) Detected class org.bukkit.event.block.BlockExplodeEvent
[16:40:01 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[16:40:01 INFO]: [PlaceholderAPI] Successfully registered expansion: permission [1.0.0]
[16:40:01 INFO]: [PlaceholderAPI] Successfully registered expansion: player [2.0.4]
[16:40:01 INFO]: 2 placeholder hook(s) registered!
[16:40:28 WARN]: Exception in thread "Craft Scheduler Thread - 6" 
[16:40:28 WARN]: org.apache.commons.lang.UnhandledException: Plugin Eden v1.0.37-BETA-b3dcdbf generated an exception while executing task 42
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@5bc15e8b. Client view of cluster state is {type=REPLICA_SET, servers=[{address=n1-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}, {address=n2-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]
        at com.mongodb.internal.connection.BaseCluster.createTimeoutException(BaseCluster.java:404)
        at com.mongodb.internal.connection.BaseCluster.selectServer(BaseCluster.java:123)
        at com.mongodb.internal.connection.AbstractMultiServerCluster.selectServer(AbstractMultiServerCluster.java:52)
        at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:138)
        at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
        at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:132)
        at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:86)
        at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:110)
        at com.mongodb.client.internal.MongoIterableImpl.into(MongoIterableImpl.java:122)
        at rip.diamond.practice.leaderboard.impl.KitLeaderboard.update(KitLeaderboard.java:32)
        at java.util.HashMap$Values.forEach(HashMap.java:982)
        at rip.diamond.practice.leaderboard.LeaderboardManager.update(LeaderboardManager.java:40)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more

**Comment by GoodestEnglish** [comment]
Eden cannot connect to MongoDB. Mainly because you mistyped your MongoDB information, or the database provider is down.
