### ISSUE TITLE
Problem CarbonSpigot Enable

### ISSUE THREAD

**Issue by underbone** [diamond-rip/Eden#184]
[06:58:47 ERROR]: Error occurred while enabling Eden v1.1.1-2016163 (Is it up to date?)
java.lang.NullPointerException: null
        at rip.diamond.practice.hook.HookManager.<init>(HookManager.java:24) ~[?:?]
        at rip.diamond.practice.Eden.loadManagers(Eden.java:152) ~[?:?]
        at rip.diamond.practice.Eden.onEnable(Eden.java:112) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:334) ~[CarbonSpigot.jar:git-Carbon-"38757d2"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) ~[CarbonSpigot.jar:git-Carbon-"38757d2"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:395) ~[CarbonSpigot.jar:git-Carbon-"38757d2"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:382) ~[CarbonSpigot.jar:git-Carbon-"38757d2"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:341) ~[CarbonSpigot.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:368) ~[CarbonSpigot.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:332) ~[CarbonSpigot.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:286) ~[CarbonSpigot.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:302) ~[CarbonSpigot.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:527) ~[CarbonSpigot.jar:git-Carbon-"38757d2"]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
        
        you can fix this?

**Comment by GoodestEnglish** [comment]
Can you re-download the latest version and try again? https://github.com/diamond-rip/Eden/releases/tag/1.1.1-2016163-BETA

**Comment by underbone** [comment]
okay
