### ISSUE TITLE
 yml issues

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#191]
[21:25:42 ERROR]: Could not load 'plugins/Eden-1.1.4-1f8eb9a-all.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:299) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:206) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: org.yaml.snakeyaml.error.YAMLException: java.util.zip.ZipException: invalid LOC header (bad signature)
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:200) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:381) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:232) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:157) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        ... 5 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
        at java.util.zip.ZipFile.read(Native Method) ~[?:1.8.0_312]
        at java.util.zip.ZipFile.access$1400(ZipFile.java:61) ~[?:1.8.0_312]
        at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:738) ~[?:1.8.0_312]
        at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:438) ~[?:1.8.0_312]
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_312]
        at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[?:1.8.0_312]
        at java.io.PushbackInputStream.read(PushbackInputStream.java:186) ~[?:1.8.0_312]
        at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:90) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:122) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at java.io.Reader.read(Reader.java:140) ~[?:1.8.0_312]
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:184) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:381) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:232) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:157) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        ... 5 more

**Comment by GoodestEnglish** [comment]
May you redownload Eden? Looks like the file is corrupted for some reason.

**Comment by TehJays** [comment]
it's fixed, thanks!
