### ISSUE TITLE
Problems CarbonSpigot 

### ISSUE THREAD

**Issue by underbone** [diamond-rip/Eden#22]
[06:16:57 ERROR]: Error occurred while enabling Eden v1.0.16-BETA-f684452 (Is it up to date?)
java.lang.NoClassDefFoundError: xyz/refinedev/spigot/api/handlers/impl/MovementHandler
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_312]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_312]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_312]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_312]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_312]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_312]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_312]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        at rip.diamond.practice.movement.MovementHandler.<init>(MovementHandler.java:19) ~[?:?]
        at rip.diamond.practice.movement.impl.MatchMovementHandler.<init>(MatchMovementHandler.java:20) ~[?:?]
        at rip.diamond.practice.Eden.loadGeneral(Eden.java:198) ~[?:?]
        at rip.diamond.practice.Eden.onEnable(Eden.java:109) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:329) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:410) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:374) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:329) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:296) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:569) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: xyz.refinedev.spigot.api.handlers.impl.MovementHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 30 more
[06:16:57 INFO]: [Eden] Disabling Eden v1.0.16-BETA-f684452

**Comment by underbone** [comment]
you can fix this?

**Comment by RealGoodestEnglish** [comment]
Yes for sure! What version of CarbonSpigot are you using? I will push a fix in 3 days

**Comment by underbone** [comment]
2.0

**Comment by RealGoodestEnglish** [comment]
May you please try the latest version of CarbonSpigot? 2.0 is way too old and it is not supported by the original author too.
