### ISSUE TITLE
Could not pass event InventoryClickEvent to Eden v1.1.9-BETA-7a26c9d

### ISSUE THREAD

**Issue by Prithu-K-Rai** [diamond-rip/Eden#223]
No idea why this is happening, seems to be an eden issue:

[17:03:16 INFO]: RajaSetupati issued server command: /duel O_bad
[17:03:18 ERROR]: Could not pass event InventoryClickEvent to Eden v1.1.9-BETA-7a26c9d
org.bukkit.event.EventException: null
        at xyz.refinedev.spigot.patch.eventbus.CarbonPluginLoader.lambda$createRegisteredListeners$2(Unknown Source) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:505) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:490) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1784) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:104) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:740) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:425) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:688) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:585) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.NullPointerException
        at rip.diamond.practice.duel.DuelRequestManager.verify(DuelRequestManager.java:86) ~[?:?]
        at rip.diamond.practice.duel.DuelRequestManager.sendDuelRequest(DuelRequestManager.java:24) ~[?:?]
        at rip.diamond.practice.duel.menu.ChooseKitMenu$1.clicked(ChooseKitMenu.java:62) ~[?:?]
        at rip.diamond.practice.util.menu.MenuListener.onButtonPress(MenuListener.java:50) ~[?:?]
        at rip.diamond.practice.util.menu.MenuListener$Access/0x0000000800b62840.apply(Unknown Source) ~[?:?]
        at GandDanda1.kayaFurryW(Unknown Source) ~[CarbonSpigot-v3.5.jar:?]
        at xyz.refinedev.spigot.utils.eventbusutil.methods.CallerImpl.call(Unknown Source) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at xyz.refinedev.spigot.patch.eventbus.CarbonPluginLoader.lambda$createRegisteredListeners$2(Unknown Source) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        ... 16 more
[17:03:43 INFO]: RajaSetupati issued server command: /duel O_bad
[17:03:44 ERROR]: Could not pass event InventoryClickEvent to Eden v1.1.9-BETA-7a26c9d
org.bukkit.event.EventException: null
        at xyz.refinedev.spigot.patch.eventbus.CarbonPluginLoader.lambda$createRegisteredListeners$2(Unknown Source) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:505) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:490) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1784) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:104) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:740) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:425) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:688) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:585) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.NullPointerException
        at rip.diamond.practice.duel.DuelRequestManager.verify(DuelRequestManager.java:86) ~[?:?]
        at rip.diamond.practice.duel.DuelRequestManager.sendDuelRequest(DuelRequestManager.java:24) ~[?:?]
        at rip.diamond.practice.duel.menu.ChooseKitMenu$1.clicked(ChooseKitMenu.java:62) ~[?:?]
        at rip.diamond.practice.util.menu.MenuListener.onButtonPress(MenuListener.java:50) ~[?:?]
        at rip.diamond.practice.util.menu.MenuListener$Access/0x0000000800b62840.apply(Unknown Source) ~[?:?]
        at GandDanda1.kayaFurryW(Unknown Source) ~[CarbonSpigot-v3.5.jar:?]
        at xyz.refinedev.spigot.utils.eventbusutil.methods.CallerImpl.call(Unknown Source) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at xyz.refinedev.spigot.patch.eventbus.CarbonPluginLoader.lambda$createRegisteredListeners$2(Unknown Source) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        ... 16 more
[17:03:48 INFO]: RajaSetupati issued server command: /duel O_bad
[17:03:54 INFO]: O_bad issued server command: /duel accept 58c52510-35d9-4e30-99be-9d1d918a5c67
[17:04:02 ERROR]: Could not pass event InventoryClickEvent to Eden v1.1.9-BETA-7a26c9d
org.bukkit.event.EventException: null
        at xyz.refinedev.spigot.patch.eventbus.CarbonPluginLoader.lambda$createRegisteredListeners$2(Unknown Source) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:505) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:490) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1784) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:104) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:740) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:425) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:688) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:585) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.NullPointerException
        at rip.diamond.practice.party.fight.PartyFightManager.startPartyEvent(PartyFightManager.java:43) ~[?:?]
        at rip.diamond.practice.party.fight.menu.ChooseKitMenu$1.clicked(ChooseKitMenu.java:54) ~[?:?]
        at rip.diamond.practice.util.menu.MenuListener.onButtonPress(MenuListener.java:50) ~[?:?]
        at rip.diamond.practice.util.menu.MenuListener$Access/0x0000000800b62840.apply(Unknown Source) ~[?:?]
        at GandDanda1.kayaFurryW(Unknown Source) ~[CarbonSpigot-v3.5.jar:?]
        at xyz.refinedev.spigot.utils.eventbusutil.methods.CallerImpl.call(Unknown Source) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        at xyz.refinedev.spigot.patch.eventbus.CarbonPluginLoader.lambda$createRegisteredListeners$2(Unknown Source) ~[CarbonSpigot-v3.5.jar:git-Carbon-"38757d2"]
        ... 16 more

**Comment by GoodestEnglish** [comment]
Looks like the system cannot find any arena which allows the kit you selected to run. Can you check if this version fixed your issue? If there's any now error and if issue isn't fixed, please let me know.
https://drive.google.com/file/d/18eJ4huSAeUy7F-6zke9w7Z7P9b0eA2Pj/view?usp=share_link

**Comment by oHussainBeast** [comment]
> Looks like the system cannot find any arena which allows the kit you selected to run. Can you check if this version fixed your issue? If there's any now error and if issue isn't fixed, please let me know. https://drive.google.com/file/d/18eJ4huSAeUy7F-6zke9w7Z7P9b0eA2Pj/view?usp=share_link

its fixed now
