### ISSUE TITLE
Bedwars bug

### ISSUE THREAD

**Issue by diocan** [diamond-rip/Eden#247]
bedwars bug 
 https://youtu.be/gQyZyIfwaTc 

[Eden] Task #8205 for Eden v1.1.10-BETA-805a40d generated an exception
java.lang.NoClassDefFoundError: rip/diamond/practice/Language
        at rip.diamond.spigotapi.knockback.impl.WindSpigotKnockback.applyKnockback(WindSpigotKnockback.java:16) ~[?:?]
        at rip.diamond.practice.match.Match.start(Match.java:124) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65) ~[pandaspigot-82.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:403) ~[pandaspigot-82.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:927) ~[pandaspigot-82.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[pandaspigot-82.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[pandaspigot-82.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[pandaspigot-82.jar:]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: rip.diamond.practice.Language
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[pandaspigot-82.jar:]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:89) ~[pandaspigot-82.jar:]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 9 more

**Comment by GoodestEnglish** [comment]
Try to redownload the plugin. Looks like the plugin is missing some classes when you download

**Comment by diocan** [comment]
I downloaded it again but it didn't fix

**Comment by GoodestEnglish** [comment]
Fixed in https://github.com/diamond-rip/Eden/releases/tag/1.1.11-BETA-388825c
