### ISSUE TITLE
I cant set anything in language.yml

### ISSUE THREAD

**Issue by AruentXX** [diamond-rip/Eden#275]
when i tried to do it it said

Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character          '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 14, column 1:
        - "&7"
    ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:504) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 21 more

**Comment by AruentXX** [comment]
I started having this issue after i updated to 1.1.3 and yes i updated the language.yml and config.yml

**Comment by AruentXX** [comment]
![o444k](https://user-images.githubusercontent.com/132748539/236628001-b9b11b8f-7dfd-4ebc-a97b-f2bbf100663f.png)
this is what happened when i tried to do some stuff

**Comment by AruentXX** [comment]
*when i set smth

**Comment by GoodestEnglish** [comment]
When you tries to update your config, you cannot use your tab keyboard button. You must use spacebar.

**Comment by AruentXX** [comment]
I did use spacebar tho

**Comment by GoodestEnglish** [comment]
Well, the error did say you are using tab instead of spacebar.

Try to reset your language.yml then
