### ISSUE TITLE
A Problem With My Spigot

### ISSUE THREAD

**Issue by ABIGDachshunch** [diamond-rip/Eden#30]
Error occurred while enabling Eden v1.0.18-BETA-54d3eeb (Is it up to date?)
java.lang.IncompatibleClassChangeError: Expected non-static field org.github.paperspigot.PaperSpigotWorldConfig.disablePlayerCrits
	at rip.diamond.practice.match.Match.lambda$init$0(Match.java:69) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292]
	at rip.diamond.practice.match.Match.init(Match.java:68) ~[?:?]
	at rip.diamond.practice.Eden.loadGeneral(Eden.java:193) ~[?:?]
	at rip.diamond.practice.Eden.onEnable(Eden.java:110) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:320) ~[Vega%20Spigot.jar:git-vegaSpigot-7e8d4bd]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [Vega%20Spigot.jar:git-vegaSpigot-7e8d4bd]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:409) [Vega%20Spigot.jar:git-vegaSpigot-7e8d4bd]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:296) [Vega%20Spigot.jar:git-vegaSpigot-7e8d4bd]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:255) [Vega%20Spigot.jar:git-vegaSpigot-7e8d4bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:411) [Vega%20Spigot.jar:git-vegaSpigot-7e8d4bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:375) [Vega%20Spigot.jar:git-vegaSpigot-7e8d4bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:330) [Vega%20Spigot.jar:git-vegaSpigot-7e8d4bd]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:265) [Vega%20Spigot.jar:git-vegaSpigot-7e8d4bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:568) [Vega%20Spigot.jar:git-vegaSpigot-7e8d4bd]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[03:59:39] [Server thread/INFO]: [Eden] Disabling Eden v1.0.18-BETA-54d3eeb

**Comment by HierarchyMan** [comment]
Disable boxing hit counter fix in config ig

**Comment by RealGoodestEnglish** [comment]
Looks like you are using a custom spigot fork called "VegaSpigot". Not sure what that spigot fork is but looks like that spigot fork is either not a PaperSpigot fork, or they changed how PaperSpigot config works. I would recommend you to use other spigot forks such as ImanitySpigot, CarbonSpigot or PaperSpigot, since those spigot forks are officially supported by Eden.

**Comment by ABIGDachshunch** [comment]
> 

omg it worked

**Comment by ABIGDachshunch** [comment]
thank you hierarchyman

**Comment by HierarchyMan** [comment]
happy to help :D
but i think vegaspigot is gonna have some event errors such as sumo wont work becuz its prolly based on spigotmc instead of papermc
use windspigot(best free) or pandaspigot(ehh mid free) or carbon(paid)
eden worked with these 3 for me

**Comment by ABIGDachshunch** [comment]
vega is based of sportspigot i think

**Comment by HierarchyMan** [comment]
In short try some other spigot :D
Cuz idk what sport spigot is lol

**Comment by ABIGDachshunch** [comment]
its sportpaper my bad
i write it wrong
