### ISSUE TITLE
DeluxeMenus issue,

### ISSUE THREAD

**Issue by Cryzis** [diamond-rip/Eden#346]
I've noticed that using deluxemenus with eden gives me errors. when both are installed, the server thinks there is a duplicate version of the plugin.

This only happens when the eden plugin and deluxemenus plugin are in the same server.

## logs
```
[20:52:10 ERROR]: Could not load 'plugins/DeluxeMenus-1.10.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:299) [FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:206) [FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) [FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:123) ~[FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        at com.extendedclip.deluxemenus.DeluxeMenus.<init>(DeluxeMenus.java:35) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_312]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_312]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        ... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:126) ~[FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        at net.audidevelopment.core.plugin.cCore.<init>(cCore.java:44) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_312]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_312]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[FoxSpigot_1.0.jar:1.8.8-R0.1-SNAPSHOT]
        ... 6 moresddfasd
```

**Comment by HierarchyMan** [comment]
Not possible unless there is another deluxe menu jar u didn't see in ur plugins folder
This never was an issue for me

**Comment by Chromaah** [comment]
just use bettergui, not a fan of deluxemenus

**Comment by GoodestEnglish** [comment]
There has to be another DeluxeMenus plugin in your folder. Eden doesn't touch any of stuff related to DeluxeMenus
