### ISSUE TITLE
mongodb error

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#391]
![image](https://github.com/diamond-rip/Eden/assets/132185379/b81cb700-80d8-4d4b-a0ef-3aa845d81bc7)
just updated eden and this is happening

also found this console error, i cant understand it so im just putting it here

[07:52:29 ERROR]: Cannot load plugins/Eden/config.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 2, column 1:
    debug: false
    ^
expected <block end>, but found BlockMappingStart
 in 'string', line 60, column 2:
     queue:
     ^
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[WindSpigot-2.1.2.jar:]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:228) ~[WindSpigot-2.1.2.jar:]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[WindSpigot-2.1.2.jar:]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) ~[WindSpigot-2.1.2.jar:]
        at rip.diamond.practice.util.BasicConfigFile.<init>(BasicConfigFile.java:32) ~[?:?]
        at rip.diamond.practice.Eden.loadFiles(Eden.java:136) ~[?:?]
        at rip.diamond.practice.Eden.onEnable(Eden.java:109) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:326) ~[WindSpigot-2.1.2.jar:]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) ~[WindSpigot-2.1.2.jar:]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:400) ~[WindSpigot-2.1.2.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:451) ~[WindSpigot-2.1.2.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:409) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:443) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:407) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:367) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:327) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:620) ~[WindSpigot-2.1.2.jar:]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 2, column 1:
    debug: false
    ^
expected <block end>, but found BlockMappingStart
 in 'string', line 60, column 2:
     queue:
     ^
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[WindSpigot-2.1.2.jar:]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[WindSpigot-2.1.2.jar:]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[WindSpigot-2.1.2.jar:]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[WindSpigot-2.1.2.jar:]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[WindSpigot-2.1.2.jar:]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[WindSpigot-2.1.2.jar:]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[WindSpigot-2.1.2.jar:]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[WindSpigot-2.1.2.jar:]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[WindSpigot-2.1.2.jar:]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[WindSpigot-2.1.2.jar:]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[WindSpigot-2.1.2.jar:]
        ... 17 more

**Comment by GoodestEnglish** [comment]
Looks like you made a styling error in your config.yml while updating your config.
May you send your config.yml? (Ofc remove ur mongodb info first)

**Comment by serumanooo** [comment]
> Looks like you made a styling error in your config.yml while updating your config. May you send your config.yml? (Ofc remove ur mongodb info first)

[config (3).txt](https://github.com/diamond-rip/Eden/files/11891920/config.3.txt)

**Comment by serumanooo** [comment]
> > Looks like you made a styling error in your config.yml while updating your config. May you send your config.yml? (Ofc remove ur mongodb info first)
> 
> [config (3).txt](https://github.com/diamond-rip/Eden/files/11891920/config.3.txt) i dont think i mistyped something because hierarchyman told me that it also happened with him ![image](https://user-images.githubusercontent.com/132185379/249401935-70c1099a-35ab-42b5-bbf7-3603ea834006.png)

yes i mistyped something, im going to fix it
