### ISSUE TITLE
Sumo Event Not Teleporting after winning round

### ISSUE THREAD

**Issue by pixeledge-verify** [diamond-rip/Eden#394]
![image](https://github.com/diamond-rip/Eden/assets/58975768/841cd124-e77a-4b71-987e-0979bc4c23ce)
So yea this happened...

**Comment by pixeledge-verify** [comment]
nope, also using ImanitySpigot 3
with imanity teleport on

**Comment by pixeledge-verify** [comment]
also suggestion that there should be a player spectate item or command like /event spectate. To spectate event players

**Comment by pixeledge-verify** [comment]
also potion effects doesn't reset in time based modes

**Comment by pixeledge-verify** [comment]
round based*

**Comment by pixeledge-verify** [comment]
![image](https://github.com/diamond-rip/Eden/assets/58975768/9cec26ab-3b90-47ad-98a3-d272e4781e85)
@GoodestEnglish Uh so sometimes the Event Works and Sometimes it just doesn't. Below is Console Error.

```
[12:42:44 ERROR]: Could not pass event MatchEndEvent to Eden v1.1.20-BETA-1b8a69d
java.lang.NullPointerException: Cannot invoke "rip.diamond.practice.match.team.Team.getLeader()" because "team" is null
        at rip.diamond.practice.events.EdenEvent.getTeamName(EdenEvent.java:64) ~[?:?]
        at rip.diamond.practice.events.impl.Tournament$1.onMatchEnd(Tournament.java:72) ~[?:?]
        at org.imanity.imanityspigot.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:47) ~[spigot.jar:git-iSpigot-PaperEdition]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510) ~[spigot.jar:git-iSpigot-PaperEdition]
        at rip.diamond.practice.util.BaseEvent.call(BaseEvent.java:15) ~[?:?]
        at rip.diamond.practice.match.Match.end(Match.java:260) ~[?:?]
        at rip.diamond.practice.match.Match.start(Match.java:88) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(SourceFile:410) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1035) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:947) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:837) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

Could you please solve this quick, we have a event in like 3 hours. Would be really great if it were fixed.

**Comment by pixeledge-verify** [comment]
Also is there any permission for staffs to spectate user silently?

**Comment by GoodestEnglish** [comment]
> ![image](https://github.com/diamond-rip/Eden/assets/58975768/9cec26ab-3b90-47ad-98a3-d272e4781e85)
> 
> @GoodestEnglish Uh so sometimes the Event Works and Sometimes it just doesn't. Below is Console Error.
> 
> 
> 
> ```
> 
> [12:42:44 ERROR]: Could not pass event MatchEndEvent to Eden v1.1.20-BETA-1b8a69d
> 
> java.lang.NullPointerException: Cannot invoke "rip.diamond.practice.match.team.Team.getLeader()" because "team" is null
> 
>         at rip.diamond.practice.events.EdenEvent.getTeamName(EdenEvent.java:64) ~[?:?]
> 
>         at rip.diamond.practice.events.impl.Tournament$1.onMatchEnd(Tournament.java:72) ~[?:?]
> 
>         at org.imanity.imanityspigot.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:47) ~[spigot.jar:git-iSpigot-PaperEdition]
> 
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot.jar:git-iSpigot-PaperEdition]
> 
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
> 
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[spigot.jar:git-iSpigot-PaperEdition]
> 
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510) ~[spigot.jar:git-iSpigot-PaperEdition]
> 
>         at rip.diamond.practice.util.BaseEvent.call(BaseEvent.java:15) ~[?:?]
> 
>         at rip.diamond.practice.match.Match.end(Match.java:260) ~[?:?]
> 
>         at rip.diamond.practice.match.Match.start(Match.java:88) ~[?:?]
> 
>         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) ~[spigot.jar:git-iSpigot-PaperEdition]
> 
>         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(SourceFile:410) ~[spigot.jar:git-iSpigot-PaperEdition]
> 
>         at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1035) ~[spigot.jar:git-iSpigot-PaperEdition]
> 
>         at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502) ~[spigot.jar:git-iSpigot-PaperEdition]
> 
>         at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:947) ~[spigot.jar:git-iSpigot-PaperEdition]
> 
>         at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:837) ~[spigot.jar:git-iSpigot-PaperEdition]
> 
>         at java.lang.Thread.run(Thread.java:833) [?:?]
> 
> ```
> 
> 
> 
> Could you please solve this quick, we have a event in like 3 hours. Would be really great if it were fixed.

Looks like the tournament is using the same arena somehow. I will look into it.

Note that I am still having school during summer and currently it is midterm period in summer, I couldn't check issues often.

**Comment by GoodestEnglish** [comment]
> Also is there any permission for staffs to spectate user silently?
> 
> 

There isn't as of right now. Eden is going to implement a custom staff mode which allows staff to moderate players easily. (Coming soon after I recode arena generation)

**Comment by pixeledge-verify** [comment]
> > ![image](https://user-images.githubusercontent.com/58975768/250275413-9cec26ab-3b90-47ad-98a3-d272e4781e85.png)
> > @GoodestEnglish Uh so sometimes the Event Works and Sometimes it just doesn't. Below is Console Error.
> > ```
> > 
> > [12:42:44 ERROR]: Could not pass event MatchEndEvent to Eden v1.1.20-BETA-1b8a69d
> > 
> > java.lang.NullPointerException: Cannot invoke "rip.diamond.practice.match.team.Team.getLeader()" because "team" is null
> > 
> >         at rip.diamond.practice.events.EdenEvent.getTeamName(EdenEvent.java:64) ~[?:?]
> > 
> >         at rip.diamond.practice.events.impl.Tournament$1.onMatchEnd(Tournament.java:72) ~[?:?]
> > 
> >         at org.imanity.imanityspigot.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:47) ~[spigot.jar:git-iSpigot-PaperEdition]
> > 
> >         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot.jar:git-iSpigot-PaperEdition]
> > 
> >         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
> > 
> >         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[spigot.jar:git-iSpigot-PaperEdition]
> > 
> >         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510) ~[spigot.jar:git-iSpigot-PaperEdition]
> > 
> >         at rip.diamond.practice.util.BaseEvent.call(BaseEvent.java:15) ~[?:?]
> > 
> >         at rip.diamond.practice.match.Match.end(Match.java:260) ~[?:?]
> > 
> >         at rip.diamond.practice.match.Match.start(Match.java:88) ~[?:?]
> > 
> >         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) ~[spigot.jar:git-iSpigot-PaperEdition]
> > 
> >         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(SourceFile:410) ~[spigot.jar:git-iSpigot-PaperEdition]
> > 
> >         at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1035) ~[spigot.jar:git-iSpigot-PaperEdition]
> > 
> >         at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502) ~[spigot.jar:git-iSpigot-PaperEdition]
> > 
> >         at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:947) ~[spigot.jar:git-iSpigot-PaperEdition]
> > 
> >         at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:837) ~[spigot.jar:git-iSpigot-PaperEdition]
> > 
> >         at java.lang.Thread.run(Thread.java:833) [?:?]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you please solve this quick, we have a event in like 3 hours. Would be really great if it were fixed.
> 
> Looks like the tournament is using the same arena somehow. I will look into it.
> 
> Note that I am still having school during summer and currently it is midterm period in summer, I couldn't check issues often.

ah i see, but are you aware of any temporary fixes which I can use for now?

**Comment by GoodestEnglish** [comment]
Try this version and let me know if this version fixed the tournament cannot start issue: https://drive.google.com/file/d/1pSR18WwsjtQ8avA9MrH3MjVZoubBu1YE/view?usp=sharing

**Comment by pixeledge-verify** [comment]
> Try this version and let me know if this version fixed the tournament cannot start issue: https://drive.google.com/file/d/1pSR18WwsjtQ8avA9MrH3MjVZoubBu1YE/view?usp=sharing

Wait testing

**Comment by pixeledge-verify** [comment]
> > > ![image](https://user-images.githubusercontent.com/58975768/250275413-9cec26ab-3b90-47ad-98a3-d272e4781e85.png)
> > > @GoodestEnglish Uh so sometimes the Event Works and Sometimes it just doesn't. Below is Console Error.
> > > ```
> > > 
> > > [12:42:44 ERROR]: Could not pass event MatchEndEvent to Eden v1.1.20-BETA-1b8a69d
> > > 
> > > java.lang.NullPointerException: Cannot invoke "rip.diamond.practice.match.team.Team.getLeader()" because "team" is null
> > > 
> > >         at rip.diamond.practice.events.EdenEvent.getTeamName(EdenEvent.java:64) ~[?:?]
> > > 
> > >         at rip.diamond.practice.events.impl.Tournament$1.onMatchEnd(Tournament.java:72) ~[?:?]
> > > 
> > >         at org.imanity.imanityspigot.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:47) ~[spigot.jar:git-iSpigot-PaperEdition]
> > > 
> > >         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot.jar:git-iSpigot-PaperEdition]
> > > 
> > >         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
> > > 
> > >         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[spigot.jar:git-iSpigot-PaperEdition]
> > > 
> > >         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510) ~[spigot.jar:git-iSpigot-PaperEdition]
> > > 
> > >         at rip.diamond.practice.util.BaseEvent.call(BaseEvent.java:15) ~[?:?]
> > > 
> > >         at rip.diamond.practice.match.Match.end(Match.java:260) ~[?:?]
> > > 
> > >         at rip.diamond.practice.match.Match.start(Match.java:88) ~[?:?]
> > > 
> > >         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) ~[spigot.jar:git-iSpigot-PaperEdition]
> > > 
> > >         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(SourceFile:410) ~[spigot.jar:git-iSpigot-PaperEdition]
> > > 
> > >         at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1035) ~[spigot.jar:git-iSpigot-PaperEdition]
> > > 
> > >         at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502) ~[spigot.jar:git-iSpigot-PaperEdition]
> > > 
> > >         at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:947) ~[spigot.jar:git-iSpigot-PaperEdition]
> > > 
> > >         at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:837) ~[spigot.jar:git-iSpigot-PaperEdition]
> > > 
> > >         at java.lang.Thread.run(Thread.java:833) [?:?]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Could you please solve this quick, we have a event in like 3 hours. Would be really great if it were fixed.
> > 
> > 
> > Looks like the tournament is using the same arena somehow. I will look into it.
> > Note that I am still having school during summer and currently it is midterm period in summer, I couldn't check issues often.
> 
> ah i see, but are you aware of any temporary fixes which I can use for now?

Just Tested it, it's working .

Will host a larger event in like 45 minutes

**Comment by pixeledge-verify** [comment]
@GoodestEnglish 

Running Great
![Screenshot (766)](https://github.com/diamond-rip/Eden/assets/58975768/4424a6fc-51e6-4b5d-8234-f8d0d5c2027c)

**Comment by pixeledge-verify** [comment]
@GoodestEnglish The Fireball KB gets messed up sometimes and throws you around sometimes

**Comment by pixeledge-verify** [comment]
![image](https://github.com/diamond-rip/Eden/assets/58975768/226c2f7d-6d3a-4bc4-b058-928b629a0d7a)
Did another event, working great too.

**Comment by HierarchyMan** [comment]
> @GoodestEnglish The Fireball KB gets messed up sometimes and throws you around sometimes
> 

Must be your spigot
Fireball kb works as expected for me with no exceptions

**Comment by GoodestEnglish** [comment]
> @GoodestEnglish The Fireball KB gets messed up sometimes and throws you around sometimes
> 
> 

Noted. Will look into it

**Comment by HierarchyMan** [comment]
> > @GoodestEnglish The Fireball KB gets messed up sometimes and throws you around sometimes
> > 
> > 
> 
> Noted. Will look into it 

It's fine for me while using any other spigot lol
