### ISSUE TITLE
Critical Match End Bug

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#430]
After match ends this error is generated in console and match goes on infinitely

Could not pass event PlayerDeathEvent to Eden v1.1.22-BETA-8bc50aa
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[server.jar:]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[server.jar:]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[server.jar:]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[server.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:496) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:487) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:872) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:849) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:562) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1066) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1198) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1710) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:39) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:7) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:203) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:544) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:44) ~[server.jar:]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[server.jar:]
        at me.filoghost.holographicdisplays.nms.v1_8_R3.InboundPacketHandler.channelRead(InboundPacketHandler.java:43) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[server.jar:]
        at io.github.repooper.packetevents.Vulcan_iu.channelRead(Vulcan_iu.java:39) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:28) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[server.jar:]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[server.jar:]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[server.jar:]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[server.jar:]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[server.jar:]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_312]
        at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_312]
        at rip.diamond.practice.config.Config.toStringList(Config.java:128) ~[?:?]
        at rip.diamond.practice.match.impl.SoloMatch.calculateMatchStats(SoloMatch.java:127) ~[?:?]
        at rip.diamond.practice.match.Match.end(Match.java:285) ~[?:?]
        at rip.diamond.practice.match.Match.end(Match.java:254) ~[?:?]
        at rip.diamond.practice.match.Match.die(Match.java:211) ~[?:?]
        at rip.diamond.practice.match.listener.MatchListener.onDeath(MatchListener.java:176) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[server.jar:]
        ... 67 more

**Comment by HierarchyMan** [comment]
i deleted my config and generated a new one the bug still persists

**Comment by HierarchyMan** [comment]
new eden is really bugg also cracshes the server after a few mins

**Comment by RainFallDev** [comment]
yes i have this bug too

**Comment by RainFallDev** [comment]
i dont have this bug delete config.yml

**Comment by Chromaah** [comment]
I was literally JUST about to open an issue about this lmao

**Comment by Chromaah** [comment]
hope an update is pushed out ASAP, needed.

**Comment by RainFallDev** [comment]
@GoodestEnglish

**Comment by GoodestEnglish** [comment]
Hotfix coming soon



> new eden is really bugg also cracshes the server after a few mins

Whats the error caused the server to crash?

**Comment by HierarchyMan** [comment]
> Hotfix coming soon
> 
> > new eden is really bugg also cracshes the server after a few mins
> 
> Whats the error caused the server to crash?

it was an out of memory error caused due to databse stuff by aquacore becuase aquacore uses some of eden placeholders
so im sure exactly sure if it was eden but ive allocated more ram and it didnt crash

**Comment by RainFallDev** [comment]
can you fix game not ending @GoodestEnglish

**Comment by RainFallDev** [comment]
this is big bug

**Comment by RainFallDev** [comment]
please fix

**Comment by GoodestEnglish** [comment]
> please fix

Working on it in 5am :) Should push an update within an hour

**Comment by RainFallDev** [comment]
ok

**Comment by GoodestEnglish** [comment]
Fixed in latest release. https://github.com/diamond-rip/Eden/releases/tag/1.1.23-BETA-64b4613

Apologize for the issues. I will still be on for one more hour to see if any critical bugs still exists.

**Comment by RainFallDev** [comment]
Thanks

**Comment by RainFallDev** [comment]
@GoodestEnglish game end bug not fixed

**Comment by Chromaah** [comment]
Yep, fixed in latest update
