### ISSUE TITLE
Won't load


### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#46]
Error: 
[03:39:46 INFO]: [ViaVersion] Enabling ViaVersion v4.1.1
[03:39:46 INFO]: [Eden] Enabling Eden v1.0.23-BETA-405317f
[03:39:46 ERROR]: Error occurred while enabling Eden v1.0.23-BETA-405317f (Is it up to date?)
java.lang.NoClassDefFoundError: org/imanity/imanityspigot/movement/MovementHandler
        at rip.diamond.spigotapi.SpigotType.<clinit>(SpigotType.java:22) ~[?:?]
        at rip.diamond.spigotapi.SpigotAPI.init(SpigotAPI.java:22) ~[?:?]
        at rip.diamond.practice.Eden.onEnable(Eden.java:106) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
Caused by: java.lang.ClassNotFoundException: org.imanity.imanityspigot.movement.MovementHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_352]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_352]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_352]
        ... 14 more
[03:39:46 INFO]: [Eden] Disabling Eden v1.0.23-BETA-405317f

Plugins:
FastAsyncWorldEdit, ProtocolSupport, WorldEdit, ViaVersion, ProtocolLib, Eden

Spigot: PaperSpigot official
And yes I did disable imanity options in config

**Comment by HierarchyMan** [comment]
Am I doing something wrong?

**Comment by GoodestEnglish** [comment]
I will work on a fix tomorrow, by now please add `-noverify` in your startup jvm arguments

**Comment by HierarchyMan** [comment]
Ok

**Comment by HierarchyMan** [comment]
![Screenshot_2023-01-04-10-45-06-70_568ed85dd9b4e5f606052ed6d65243e4.jpg](https://user-images.githubusercontent.com/97939376/210488930-5361383d-58a0-4652-b9df-51d1f2e1a332.jpg)

Works

**Comment by HierarchyMan** [comment]
Wow golden head and kit saving also fixed noice
