### ISSUE TITLE
just an error

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#462]
[11:31:49 INFO]: serumano_ issued server command: /save-all
[11:31:49 WARN]: java.io.FileNotFoundException: ./citadel/level.dat_new (Permission denied)
[11:31:49 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[11:31:49 WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[11:31:49 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[11:31:49 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.WorldNBTStorage.saveWorldData(WorldNBTStorage.java:141)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.ServerNBTManager.saveWorldData(SourceFile:43)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:1061)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.save(WorldServer.java:1022)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.CommandSaveAll.execute(SourceFile:37)
[11:31:49 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:146)
[11:31:49 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:60)
[11:31:49 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161)
[11:31:49 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:775)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1490)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1294)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:56)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:7)
[11:31:49 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11:31:49 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:918)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854)
[11:31:49 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707)
[11:31:49 WARN]:        at java.lang.Thread.run(Thread.java:748)

i dont really know what is this error so im posting it here

**Comment by serumanooo** [comment]
> #read-the-error 💀 Remove/Delete session.lock from your world folder Or better yet Don't use multiple worlds

ok ty

**Comment by HierarchyMan** [comment]
> > #read-the-error 💀 Remove/Delete session.lock from your world folder Or better yet Don't use multiple worlds
> 
> ok ty

If it's still not working then copy the region and dim files to a new copy of a working world
