### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#466]
my server lagged for some seconds and i got this error in console, so i think i should report it here

[15:22:22 WARN]: [Eden] Task #170437 for Eden v1.1.26-BETA-79af067 generated an exception
java.lang.NullPointerException: null
        at rip.diamond.practice.util.VisibilityController.shouldSeePlayer(VisibilityController.java:68) ~[?:?]
        at rip.diamond.practice.util.VisibilityController.lambda$updateVisibility$0(VisibilityController.java:29) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65) ~[WindSpigot-2.1.2.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:403) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:927) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[WindSpigot-2.1.2.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[WindSpigot-2.1.2.jar:]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]

**Comment by GoodestEnglish** [comment]
Currently how the plugin handles visibility is kinda unoptimized. It is planned to have a recode.

But the current system should work (I guess :/). I've also saw another issues you've opened which mentions about /skin. Does this error still occurs when no one uses /skin?

**Comment by serumanooo** [comment]
> Currently how the plugin handles visibility is kinda unoptimized. It is planned to have a recode.
> 
> But the current system should work (I guess :/). I've also saw another issues you've opened which mentions about /skin. Does this error still occurs when no one uses /skin?

I dont really know, idk if i csn but ill try to check if it still occurs when no one uses /skin

**Comment by serumanooo** [comment]
@GoodestEnglish i know its not related to eden but do you know how can i fix this? :(
![image](https://github.com/diamond-rip/Eden/assets/132185379/0f4060f2-91bb-46d6-ab26-e5395533e250)
