### ISSUE TITLE
cannot enable Eden

### ISSUE THREAD

**Issue by Zhuyuan0907** [diamond-rip/Eden#48]
[23:03:52 INFO]: [Eden] Enabling Eden v1.0.23-BETA-405317f
[23:03:52 ERROR]: Error occurred while enabling Eden v1.0.23-BETA-405317f (Is it up to date?)
java.lang.NoClassDefFoundError: xyz/refinedev/spigot/api/handlers/impl/MovementHandler
        at rip.diamond.spigotapi.SpigotType.<clinit>(SpigotType.java:23) ~[?:?]
        at rip.diamond.spigotapi.SpigotAPI.init(SpigotAPI.java:22) ~[?:?]
        at rip.diamond.practice.Eden.onEnable(Eden.java:106) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:439) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:398) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:505) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:430) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:398) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:388) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:728) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: xyz.refinedev.spigot.api.handlers.impl.MovementHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 14 more
[23:03:52 INFO]: [Eden] Disabling Eden v1.0.23-BETA-405317f

using iSpigot

**Comment by HierarchyMan** [comment]
Use -noverify in launch args

**Comment by Zhuyuan0907** [comment]
> Use -noverify in launch args duplicate #46

oh i see
can I see your Practice server?
I'm curious what the server made by others looks like ww

**Comment by GoodestEnglish** [comment]
Fixed in latest version
