### ISSUE TITLE
dataase error

### ISSUE THREAD

**Issue by DaddySuff** [diamond-rip/Eden#500]
[03:40:22 INFO]: Closed connection [connectionId{localValue:2}] to blzh6zwpq6ocdosecspy-mongodb.services.clever-cloud.com:2582 because there was a socket exception raised by this connection.
[03:40:22 WARN]: Exception in thread "Craft Scheduler Thread - 7" 
[03:40:22 WARN]: org.apache.commons.lang.UnhandledException: Plugin Eden v1.1.27-BETA-e9c7ad6 generated an exception while executing task 44
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-256, userName='ufg2pqulb3zg17fs7gax', source='blzh6zwpq6ocdosecspy', password=<hidden>, mechanismProperties={}}
        at com.mongodb.internal.connection.SaslAuthenticator.wrapException(SaslAuthenticator.java:173)
        at com.mongodb.internal.connection.SaslAuthenticator.access$300(SaslAuthenticator.java:40)
        at com.mongodb.internal.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:70)
        at com.mongodb.internal.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:47)
        at com.mongodb.internal.connection.SaslAuthenticator.doAsSubject(SaslAuthenticator.java:179)
        at com.mongodb.internal.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:47)
        at com.mongodb.internal.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:152)
        at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:63)
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:127)
        at com.mongodb.internal.connection.UsageTrackingInternalConnection.open(UsageTrackingInternalConnection.java:50)
        at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.open(DefaultConnectionPool.java:390)
        at com.mongodb.internal.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:106)
        at com.mongodb.internal.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:92)
        at com.mongodb.internal.connection.DefaultServer.getConnection(DefaultServer.java:85)
        at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:115)
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:460)
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:406)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:696)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:83)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
        at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:132)
        at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:86)
        at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:110)
        at com.mongodb.client.internal.MongoIterableImpl.into(MongoIterableImpl.java:122)
        at rip.diamond.practice.leaderboard.impl.KitLeaderboard.update(KitLeaderboard.java:32)
        at java.util.HashMap$Values.forEach(HashMap.java:982)
        at rip.diamond.practice.leaderboard.LeaderboardManager.update(LeaderboardManager.java:41)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more
Caused by: com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed): 'Authentication failed.' on server blzh6zwpq6ocdosecspy-mongodb.services.clever-cloud.com:2582. The full response is {"ok": 0.0, "errmsg": "Authentication failed.", "code": 18, "codeName": "AuthenticationFailed"}
        at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
        at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:299)
        at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
        at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:83)
        at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:33)
        at com.mongodb.internal.connection.SaslAuthenticator.sendSaslContinue(SaslAuthenticator.java:134)
        at com.mongodb.internal.connection.SaslAuthenticator.access$200(SaslAuthenticator.java:40)
        at com.mongodb.internal.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:67)
        ... 30 more

**Comment by GoodestEnglish** [comment]
You have wrong mongodb info in config.yml.
