### ISSUE TITLE
error

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#513]
[23:57:21 ERROR]: Could not pass event BlockFromToEvent to Eden v1.1.27-BETA-e9c7ad6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.BlockFlowing.b(BlockFlowing.java:148) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:684) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:249) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469) ~[?:1.8.0_312]
        at java.util.HashMap$ValueIterator.next(HashMap.java:1498) ~[?:1.8.0_312]
        at rip.diamond.practice.match.listener.MatchListener.onBlockFromTo(MatchListener.java:738) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 12 more

**Comment by serumanooo** [comment]
@GoodestEnglish more errors
[2023-08-07-4.log](https://github.com/diamond-rip/Eden/files/12286390/2023-08-07-4.log)


also some players at my server are reporting an issue where the opponent player is invisible

**Comment by serumanooo** [comment]
also, i got this error message
![image](https://github.com/diamond-rip/Eden/assets/132185379/95e5e492-fc06-4fb7-9049-2e6b1bf835a9)

it does not affect anything, i can play, i can do /stats, but its annoying to see this everytime i join at the server
and is there a way to customize/remove this message? i didnt found it at language,yml

(didnt wanted to open a new issue)

**Comment by GoodestEnglish** [comment]
> also, i got this error message ![image](https://user-images.githubusercontent.com/132185379/258968998-95e5e492-fc06-4fb7-9049-2e6b1bf835a9.png)
> 
> it does not affect anything, i can play, i can do /stats, but its annoying to see this everytime i join at the server and is there a way to customize/remove this message? i didnt found it at language,yml
> 
> (didnt wanted to open a new issue)

Will be customizeable in the next version
