### ISSUE TITLE
Toggle Item Flags error

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#520]
[06:42:09 INFO]: cystol issued server command: /toggleitemflag
[06:42:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'toggleitemflag' in rip.diamond.practice.util.command.Command$CommandExecutor(toggleitemflag)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[server.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:775) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1490) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1294) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:56) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:7) ~[server.jar:]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:918) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[server.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[server.jar:]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at rip.diamond.practice.misc.commands.ToggleItemFlagCommand.execute(ToggleItemFlagCommand.java:28) ~[?:?]
        at rip.diamond.practice.util.command.Command$CommandExecutor.execute(Command.java:99) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[server.jar:]
        ... 14 more
        
        Spigot WindSpigot
        also tested with paper
        main error Snippet: ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

**Comment by GoodestEnglish** [comment]
/toggleitemflag {ItemFlag} - To toggle the holding item's itemflag. For example, '/toggleitemflag

You need to insert the itemflag too. But I should make an error handling too. So it is also something I need to fix.

**Comment by HierarchyMan** [comment]
K thanks
