### ISSUE TITLE
placeholders error

### ISSUE THREAD

**Issue by arm4xlll** [diamond-rip/Eden#521]
when i try use placeholder eden winstreak i get this error 
syntax - %eden_leaderboard_winstreak_winstreak_sumo_1% - %eden_leaderboard_winstreak_player_sumo_1%

```
[11:46:30 WARN]: java.lang.NullPointerException
[11:46:30 WARN]:        at rip.diamond.practice.hook.plugin.placeholderapi.EdenPlaceholderExpansion.onPlaceholderRequest(EdenPlaceholderExpansion.java:259)
[11:46:30 WARN]:        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
[11:46:30 WARN]:        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[11:46:30 WARN]:        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[11:46:30 WARN]:        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[11:46:30 WARN]:        at rip.diamond.practice.hook.plugin.placeholderapi.PlaceholderAPIHook.setPlaceholders(PlaceholderAPIHook.java:9)
[11:46:30 WARN]:        at rip.diamond.practice.config.Language.translate(Language.java:773)
[11:46:30 WARN]:        at rip.diamond.practice.config.Language.toStringList(Language.java:724)
[11:46:30 WARN]:        at rip.diamond.practice.queue.menu.QueueMenu$1.getButtonItem(QueueMenu.java:96)
[11:46:30 WARN]:        at rip.diamond.practice.util.menu.Menu.createItemStack(Menu.java:39)
[11:46:30 WARN]:        at rip.diamond.practice.util.menu.Menu.openMenu(Menu.java:80)
[11:46:30 WARN]:        at rip.diamond.practice.queue.command.QueueCommand.execute(QueueCommand.java:56)
[11:46:30 WARN]:        at rip.diamond.practice.util.command.Command$CommandExecutor.execute(Command.java:99)
[11:46:30 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[11:46:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:683)
[11:46:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:426)
[11:46:30 WARN]:        at rip.diamond.practice.util.Util.performCommand(Util.java:76)
[11:46:30 WARN]:        at rip.diamond.practice.profile.listener.ProfileListener.onInteract(ProfileListener.java:122)
[11:46:30 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:46:30 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:46:30 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:46:30 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[11:46:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[11:46:30 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[11:46:30 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:46:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[11:46:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[11:46:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231)
[11:46:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195)
[11:46:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191)
[11:46:30 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:726)
[11:46:30 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
[11:46:30 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5)
[11:46:30 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[11:46:30 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[11:46:30 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[11:46:30 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[11:46:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.tickServer(MinecraftServer.java:739)
[11:46:30 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.tickServer(DedicatedServer.java:342)
[11:46:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:679)
[11:46:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:585)
[11:46:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by arm4xlll** [comment]
litelightspigot

**Comment by GoodestEnglish** [comment]
Either the kit did not exists, or the kit is newly created. Try to save the kits and restart the server.

**Comment by arm4xlll** [comment]
I tried to display the winstrike leaderboard in the menu, how can I specify a placeholder so that it displays the statistics of the kit that the player hovered over?

**Comment by GoodestEnglish** [comment]
You are using the right placeholder, but just need to wait for the leaderboard to update. 

Better just to restart the server to fix this.

**Comment by arm4xlll** [comment]
это скорее всего баг, никакая перезагрузка не помогает, вот как это выглядит в конфиге
![image](https://github.com/diamond-rip/Eden/assets/109166895/eb06b148-8b9a-4bc1-9725-74aa31c04dae)

**Comment by GoodestEnglish** [comment]
It is because `{2}` actually returns the display name of the kit, not the kit raw name.
Also you cannot do like that. You have to specify the name of the kit yourself. You cannot use placeholder inside of a placeholder.

**Comment by arm4xlll** [comment]
ok, thanks
