### ISSUE TITLE
hotbar shit error

### ISSUE THREAD

**Issue by MrCreeperMC** [diamond-rip/Eden#525]
I got this error when i join server (i dont get any items)

**java.lang.NullPointerException: null
	at rip.diamond.practice.EdenItems.giveItem(EdenItems.java:41) ~[?:?]
	at rip.diamond.practice.profile.PlayerProfile.setupItems(PlayerProfile.java:151) ~[?:?]
	at rip.diamond.practice.lobby.LobbyManager.reset(LobbyManager.java:49) ~[?:?]
	at rip.diamond.practice.lobby.LobbyManager.lambda$sendToSpawnAndReset$1(LobbyManager.java:55) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:54) ~[server.jar:1.8.8-R0.2-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:333) ~[server.jar:1.8.8-R0.2-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(Unknown Source) ~[server.jar:1.8.8-R0.2-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(Unknown Source) ~[server.jar:1.8.8-R0.2-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(Unknown Source) ~[server.jar:1.8.8-R0.2-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$1(Unknown Source) ~[server.jar:1.8.8-R0.2-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_312]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_312]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]**

**Comment by Antoniova1** [comment]
what version of eden do you have and what spigot are you using

**Comment by MrCreeperMC** [comment]
lastest - vortex spigot

**Comment by MrCreeperMC** [comment]
i mean lastest eden not vortex

**Comment by GoodestEnglish** [comment]
what does your item.yml looks like?

**Comment by MrCreeperMC** [comment]
Here you are
https://pastebin.com/ZL38efym

**Comment by MrCreeperMC** [comment]
I changed it many times but but it doesnt looks different

**Comment by MrCreeperMC** [comment]
I tried with default paper, sportpaper and atomspigot. No matter the spigot. I think when i change item type in item.yml this happen. Like kit editor is a book, I change it into anvil.

**Comment by MrCreeperMC** [comment]
And i have a question
What's the best spigot to use with Eden?

**Comment by GoodestEnglish** [comment]
![image](https://github.com/diamond-rip/Eden/assets/45838505/c80d8e34-3be4-4266-b54a-a0c9fa01d33a)
This didn't happen for me. Tested with carbonspigot and paperspigot.
Maybe try to redownload the jar file?
